Added：パイプから標準入力を受け取れるように修正
furusax0621/go-nabeatsu pull request #6
Opened 2022-01-23 01:54 UTC by nao1215

指示を受けたので……ちょっと改善を……
![image](https://user-images.githubusercontent.com/22737008/150661526-89bb6b05-e40a-459f-bde4-48f312622d61.png)

## 従来の使い方
```
$ ./main 12
ｼﾞｭｳﾆwww
```

## 本Pull Requestで出来ること
パイプに対応したので、seqコマンドで大量に数値を受け取れます。
余談ですが、"$ seq 1000000000000000000000000000000000 | ./main > test.txt"は過負荷でコマンドが落ちます。
```
$ seq 40 | ./main 
1
2
ｻｧﾝwww
4
5
ﾛｸwww
7
8
ｷｭｳwww
10
11
ｼﾞｭｳﾆwww
ｼﾞｭｳｻｧﾝwww
14
ｼﾞｭｳｺﾞwww
16
17
ｼﾞｭｳﾊﾁwww
19
20
ﾆｼﾞｭｳｲﾁwww
22
ﾆｼﾞｭｳｻｧﾝwww
ﾆｼﾞｭｳﾖﾝwww
25
26
ﾆｼﾞｭｳﾅﾅwww
28
29
ｻｧﾝｼﾞｭｳwww
ｻｧﾝｼﾞｭｳｲﾁwww
ｻｧﾝｼﾞｭｳﾆwww
ｻｧﾝｼﾞｭｳｻｧﾝwww
ｻｧﾝｼﾞｭｳﾖﾝwww
ｻｧﾝｼﾞｭｳｺﾞwww
ｻｧﾝｼﾞｭｳﾛｸwww
ｻｧﾝｼﾞｭｳﾅﾅwww
ｻｧﾝｼﾞｭｳﾊﾁwww
ｻｧﾝｼﾞｭｳｷｭｳwww
40
```

2022-02-23 13:22 UTC, furusax0621 requested changes
@nao1215 見るのをすっかり忘れていました 🙇

2022-02-23 13:22 UTC, furusax0621 commented on cmd/nabeatsu/main.go
> +			log.Fatal("パイプから入力を受け取れませんでした")
このプロダクトにロガーは不要なので標準出力にしてください 🙏

2022-02-23 13:22 UTC, furusax0621 commented on cmd/nabeatsu/main.go
> +		list := chopAll(strings.Split(string(stdin), "\n"))
`strings.Split(string(stdin), "\n")` を実行した時点で改行コードは削除されているはずなので、 `chopAll()` は冗長な気がしますね

2022-02-23 13:22 UTC, furusax0621 commented on cmd/nabeatsu/main.go
> +	return line
不要になる処理なので参考程度に見てもらえばいいですが、ここは `strings.TrimSuffix()` を使えばワンライナーで書けます
https://pkg.go.dev/strings#TrimSuffix

2022-02-24 03:23 UTC, nao1215 commented on cmd/nabeatsu/main.go
> +			log.Fatal("パイプから入力を受け取れませんでした")
標準出力に変更しました。

2022-02-24 03:24 UTC, nao1215 commented on cmd/nabeatsu/main.go
> +		list := chopAll(strings.Split(string(stdin), "\n"))
なにかの理由で必要な処理だったんですが、忘れてしまいました。
なので、chopAll() を削除しました。

2022-02-24 03:24 UTC, nao1215 commented on cmd/nabeatsu/main.go
> +	return line
:ok_man:

2022-02-24 13:18 UTC, furusax0621 approved these changes
![LGTMだにゃん](https://camo.githubusercontent.com/91500922c7a74794992482a6ec590345d1cca12070baace98e27c7d4d284247b/68747470733a2f2f696d6167652e6c67746d6f6f6e2e6465762f313339353439)

2022-02-24 13:19 UTC, merged